/**
 * @license
 * Copyright Akveo. All Rights Reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.


export const environment = {
  production: false,
  BASE_API_URL: 'https://localhost:5001/api/',
  BASE_URL_RESOURCES_LOGS: 'https://localhost:5001/resources/log/',
  BASE_URL_RESOURCES_PUNTOS: 'https://localhost:5001/resources/images/puntosturisticos/',
  BASE_URL_RESOURCES_HOSPEDAJES: 'https://localhost:5001/resources/images/hospedajes/',  
  MENSAJE_CHECKIN_MAYOR_QUE_HOY : "La fecha de check in debe ser mayor igual que hoy",
  MENSAJE_CHECKOUT_MAYOR_QUE_HOY :  "La fecha de check out debe ser mayor igual que hoy",
  MENSAJE_CHECKIN_MAYOR_QUE_CHECKOUT  : "La fecha de check out debe ser mayor que la de check in",
  NOMBRE_DOMINIO_PUNTO_TURISTICO: 'Punto Turístico',
  RUTA_LISTA_PUNTOS :'/lista-puntoturistico',
  IMAGEN_LOG: 'assets/operaciones/icons8-services-80.png',
  FORMULARIO_LISTA_TARIFAS: '/tarifa',
  DOMAIN_NAME_TARIFA: "TARIFA",
  FORMULARIO_CRUD_DEL_TARIFA: "/tarifa",
  IMAGEN_HOSPEDAJE_SELECT: 'assets/operaciones/icons8-condo-96.png',
  IMAGEN_PUNTO_SELECT: 'assets/operaciones/icons8-image-file-64.png',
  RUTA_HOME : "/",
  CREDENCIALES_INVALIDAS: "Usuario o contraseña no válido.",
  IMAGEN_FILTRAR: "assets/operaciones/icons8-conversion-80.png",
  TITULO_IMPORTAR_ARCHIVO: "Importar achivo de Hospedajes",
  SUB_TITULO_IMPORTAR_ARCHIVO: "Se debe seleccionar el archivo con datos que corresponda al formato especificado en la descripción del importador",
  IMAGEN_IMPORTAR_ARCHIVO:"",
  PAGINA_INICIAL: 0,
  HOSPEDAJE_RESERVAS: "reservas",
  END_POINT_IMPORTADOR_FUENTE: "fuentes",
  MODO_ABM_HOSPEDAJE : "crud",
  MODO_CONSULTA_HOSPEDAJE : "consulta",
  TITULO_APP: 'Bienvenidos al sitio de Hospedajes',
  SUB_TITULO_APP: 'Universidad ORT Uruguay - Diseño de Aplicaciones 2',  
  VARIABLE_QUERYSTRING_NOMBRE_PUNTO: "nombre=",    
  LOCAL_STORAGE_ADMINISTRADOR: "local_administrador",
  VERIFIFICAR_FORM_INVALIDO : "Elementos inválidos en el formulario, verifique",
  INICIO_DE_QUERYSTRING: "?",
  SEPARADOR_DE_QUERYSTRING: "&",
  MODO_UPDATE : 'UPD',
  TAB_FORM: 0,
  TAB_FOTO: 1,
  MODO_CREATE : 'INS',
  MODO_DISPLAY : 'DSP',
  MODO_DELETE : 'DEL',
  FORMULARIO_CRUD_DEL_HOSPEDAJE : "/form-hospedaje",
  END_POINT_IMPORTADOR: "importadores",
  FORMULARIO_LISTA_IMPORTADORES: "/lista-importador",
  END_POINT_ADMINISTRADOR: "administradores",    
  END_POINT_PUNTO_TURISTICO: "puntosturisticos",
  END_POINT_HOSPEDAJE: "hospedajes",
  HOSPEDAJE_PRECIOS: "precios",
  END_POINT_COMENTARIOS: "comentarios",
  END_POINT_RESERVAS: "reservas",
  END_POINT_REGION: "regiones",
  END_POINT_CATEGORIAS: "categorias",
  END_POINT_TARIFAS: "tarifas",
  RUTA_LOGIN:"/login",
  END_POINT_LOGIN: "login",
  END_POINT_PUNTO_TURISTICO_IMAGENES: "imagenes",
  END_POINT_HOSPEDAJE_IMAGENES: "imagenes",
  BARRA_DE_PATH : '/',
  END_POINT_IMPORTADOR_ARCHIVOS: 'archivos',
  AUTH : 'auth',
  TITLE_FORM_DELETE:'DELETE',
  TITLE_FORM_UPDATE:'UPDATE',
  TITLE_FORM_DISPLAY:'DISPLAY',
  TITLE_FORM_CREATE:'CREATE',
  MENSAJE_ERROR_SERVIDOR_GENERICO :"No se puede conectar con el servidor",
  SIN_IMAGEN: "assets/operaciones/icons8-no-camera-80.png",
  IMAGEN_LOADER: "loading4.gif",
  IMAGEN_ERROR_SERVIDOR: "oops.jpg",
  UPLOAD_FILE: "assets/operaciones/icons8-upload-to-the-cloud-144.png",
  MENSAJE_SIN_PUNTO_TURISTICO: "(Sin Punto Turístico)",
  MENSAJE_CONFIRMAR_ELIMINAR_FOTO :"¿Confirma eliminar la imagen?",
  MENSAJE_ERROR_AL_SUBIR_IMAGEN:'Error al subir la imagen',
  REGION_POR_DEFECTO: {id:1, nombre:""},
  SEPARADOR_DE_CATEGORIAS_CONSULTA: ",",
  FORMULARIO_CRUD_DEL_PUNTOTURISTICO : '/form-puntoturistico',
  FORMULARIO_CRUD_DEL_ADMINISTRADOR: '/form-administrador',
  FORM_CRUD_MI_ABM:'/miabm',
  VARIABLE_QUERYSTRING_REGION : "regionid=",
  VARIABLE_QUERYSTRING_PUNTOTURISTICO : "puntoturisticoid=", 
  VARIABLE_QUERYSTRING_CATEGORIAS: "&listaDeCategorias=",
  NOMBRE_ALMACENAMIENTO_DEL_FILTRO_DE_REGION : "filtroRegionListaPuntosTuristicos",
  NOMBRE_ALMACENAMIENTO_DEL_FILTRO_DE_CATEGORIAS : "filtroDeCatogoriasPuntosTuristicos",
  IMAGEN_EDITAR : "assets/operaciones/icons8-edit-property-80.png",
  IMAGEN_VISUALIZAR: "assets/operaciones/icons8-view-80.png",
  IMAGEN_ELIMINAR: "assets/operaciones/icons8-delete-bin-96.png",
  IMAGEN_CREAR: "assets/operaciones/icons8-plus-80.png",
  FORMULARIO_LISTA_ADMINISTRADORES:'/lista-administrador',
  PARAMETRO_RUTEO_ID: "id",
  PARAMETRO_RUTEO_MODO: "mode",
  PARAMETRO_RUTEO_TAB: "tab",
  NOMBRE_DOMINIO_ADMINISTRADOR : 'Administrador',
  ESTADOS_DE_RESERVA:["Creada", "PendienteDePago", "Aceptada", "Rechazada", "Expirada"],
  CANTIDAD_DE_REGISTROS_POR_PAGINA : 5,
  HOSPEDAJE_RESERVA_PUNTO_TURISTICO: "HOSPEDAJE_RESERVA_PUNTO_TURISTICO",
  HOSPEDHOSPEDAJE_RESERVA_ADULTOS: "HOSPEDHOSPEDAJE_RESERVA_ADULTOS",
  HOSPEDHOSPEDAJE_RESERVA_NINIOS: "HOSPEDHOSPEDAJE_RESERVA_NINIOS",
  HOSPEDHOSPEDAJE_RESERVA_BEBES: "HOSPEDHOSPEDAJE_RESERVA_BEBES",
  HOSPEDHOSPEDAJE_RESERVA_JUBILADOS : "HOSPEDHOSPEDAJE_RESERVA_JUBILADOS",
  HOSPEDHOSPEDAJE_RESERVA_CHECKIN : "HOSPEDHOSPEDAJE_RESERVA_CHECKIN",
  HOSPEDHOSPEDAJE_RESERVA_CHECKOUT : "HOSPEDHOSPEDAJE_RESERVA_CHECKOUT",
  LOCALE_STRING : "es",
  HOSPEDHOSPEDAJE_DTO_RESERVA_STEPPER: "HOSPEDHOSPEDAJE_DTO_RESERVA_STEPPER",
  RUTA_HOSPEDAJE_RESERVA: "/lista-hospedaje-reserva",
  MENSAJE_SE_HA_GENERADO_NUEVA_RESERVA : "Se ha generado una nueva reserva ",
  RUTA_FORM_HOSPEDAJE :'/form-hospedaje',
  RUTA_STEPPER_RESERVA : '/stepper-reserva',
  ETIQUETA_CHECK_IN : "Check In",
  ETIQUETA_CHECK_OUT : "Check Out",
  MENSAJE_FALTA_PUNTO_TURISTICO : "Debe seleccionar un punto turístico",
  MENSAJE_FALTA_FECHA_CHECKIN : "Debe indicar la fecha de checkIn",
  MENSAJE_FALTA_FECHA_CHECKOUT : "Debe indicar la fecha de checkIn",
  MENSAJE_FALTA_CANTIDAD_DE_ADULTOS : "Debe indicar la cantidad de adultos",
  MENSAJE_FALTA_CANTIDAD_DE_NINIOS : "Debe indicar la cantidad de niños",
  MENSAJE_FALTA_CANTIDAD_DE_BEBES : "Debe indicar cantidad de bebes",
  MENSAJE_FALTA_CANTIDAD_DE_JUBILADOS : "Debe indicar cantidad de jubilados",
  MENSAJE_FALTAN_HUESPEDES : "Debe haber al menos un huesped",
  PATH_IMAGENES_DE_REGIONES : 'assets/regiones/',
  PATH_IMAGENES_OPERACIONES : 'assets/operaciones/',
  PATH_RELATIVO: "~/",
  VARIABLE_QUERYSTRING_NOMBRE_HOSPEDAJE : "nombre=",
  RUTA_FORM_RESERVA : "form-reserva",
  NOMBRE_DOMINIO_RESERVA : "Reserva",
  RUTA_RESERVAS_LISTA: "/lista-reserva",
  NOMBRE_DOMINIO_COMENTARIO : "Reseña",
  NOMBRE_DOMINIO_IMPORTADOR: "Importador",
  FORMULARIO_CRUD_DEL_IMPORTADOR : "form-importador"
};
